name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  fats:
    name: FATS
    runs-on: ubuntu-latest
    env:
      CLUSTER: kind
      REGISTRY: docker-daemon
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup env
      run: |
        job=$(date +%s) # TODO use something that is assigned by CI to guarantee uniqueness
        echo "JOB_ID=${job}"
        echo "CLUSTER_NAME=cli-${job}-${{ matrix.config.qualifier }}" >> $GITHUB_ENV
        echo "NAMESPACE=cli-${job}-${{ matrix.config.qualifier }}" >> $GITHUB_ENV
        nix-env -i -f default.nix
        ./.github/workflows/kind-setup.sh
      shell: bash
    - name: Build Apps
      run: .github/workflows/build.sh
      shell: bash
